In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [8]:
class TestDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randint(2, 6, (length, size))

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

    def data(self):
        return self.data

In [9]:
ds = TestDataset(2, 10)
ds.data

tensor([[5, 5],
        [4, 3],
        [3, 5],
        [4, 3],
        [4, 5],
        [4, 5],
        [3, 4],
        [5, 5],
        [4, 4],
        [2, 3]])

In [11]:
loader = DataLoader(dataset=ds, batch_size=3, shuffle=False)

for data in loader:
    display(data)
                         

tensor([[5, 5],
        [4, 3],
        [3, 5]])

tensor([[4, 3],
        [4, 5],
        [4, 5]])

tensor([[3, 4],
        [5, 5],
        [4, 4]])

tensor([[2, 3]])

In [13]:
class TestDatasetWithTargets(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.datax = torch.randint(2, 6, (length, size))
        self.datay = torch.randint(7, 10, (length, size))

    def __getitem__(self, index):
        return self.datax[index], self.datay[index]

    def __len__(self):
        return self.len

    def print(self):
        display(self.datax)
        display(self.datay)

In [14]:
ds = TestDatasetWithTargets(2, 10)
ds.print()

tensor([[4, 4],
        [5, 2],
        [4, 2],
        [2, 2],
        [5, 3],
        [5, 4],
        [2, 5],
        [2, 4],
        [2, 3],
        [3, 2]])

tensor([[9, 9],
        [8, 8],
        [8, 9],
        [8, 7],
        [9, 9],
        [8, 7],
        [9, 9],
        [8, 8],
        [9, 8],
        [9, 8]])

In [15]:
# Testdataset is returning a tuple in this case. Dataloader adds the "minibatch" dimension for each entry in the tuple
loader = DataLoader(dataset=ds, batch_size=3, shuffle=False)

for data in loader:
    display(data)

[tensor([[4, 4],
         [5, 2],
         [4, 2]]),
 tensor([[9, 9],
         [8, 8],
         [8, 9]])]

[tensor([[2, 2],
         [5, 3],
         [5, 4]]),
 tensor([[8, 7],
         [9, 9],
         [8, 7]])]

[tensor([[2, 5],
         [2, 4],
         [2, 3]]),
 tensor([[9, 9],
         [8, 8],
         [9, 8]])]

[tensor([[3, 2]]), tensor([[9, 8]])]