In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [8]:
# create lower triangle of false and masked fill

t = torch.randn(4, 3)
tril = torch.tril(t)
mf = t.masked_fill(tril == 0, float('-inf'))
display(t, tril, mf)


tensor([[-1.0917, -2.6087, -1.7778],
        [-0.1516, -1.1200,  2.3528],
        [-0.0040,  0.2999,  0.5412],
        [-0.1545, -0.0085,  1.7611]])

tensor([[-1.0917,  0.0000,  0.0000],
        [-0.1516, -1.1200,  0.0000],
        [-0.0040,  0.2999,  0.5412],
        [-0.1545, -0.0085,  1.7611]])

tensor([[-1.0917,    -inf,    -inf],
        [-0.1516, -1.1200,    -inf],
        [-0.0040,  0.2999,  0.5412],
        [-0.1545, -0.0085,  1.7611]])